[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "WGPU backend for the Burn framework"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "wgpu", "webgpu"]
license.workspace = true
name = "burn-wgpu"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-wgpu"
version.workspace = true

[features]
autotune = ["burn-jit/autotune"]
default = ["std", "autotune", "fusion", "burn-jit/default", "cubecl/default"]
doc = ["burn-jit/doc"]
fusion = ["burn-fusion", "burn-jit/fusion"]
simple-memory-management = ["cubecl/simple-memory-management"]
std = ["burn-jit/std", "cubecl/std"]
template = ["burn-jit/template", "cubecl/template"]

[dependencies]
cubecl = { workspace = true, features = ["wgpu"] }

burn-fusion = { path = "../burn-fusion", version = "0.15.0", optional = true }
burn-jit = { path = "../burn-jit", version = "0.15.0", default-features = false }
burn-tensor = { path = "../burn-tensor", version = "0.15.0", features = [
  "cubecl-wgpu",
] }

[dev-dependencies]
burn-jit = { path = "../burn-jit", version = "0.15.0", default-features = false, features = [
  "export_tests",
] }
