[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Generic backend that can be compiled just-in-time to any shader language target"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu"]
license.workspace = true
name = "burn-jit"
readme.workspace = true
repository = "https://github.com/tracel-ai/burn/tree/main/crates/burn-jit"
version.workspace = true

[features]
autotune = []
default = ["autotune", "std", "fusion", "cubecl/default"]
doc = ["default"]
export_tests = [
  "burn-tensor-testgen",
  "serial_test",
  "burn-autodiff/export_tests",
  "burn-tensor/export_tests",
  "burn-ndarray",
  "fusion",
]
fusion = ["burn-fusion"]
std = ["cubecl/std"]
template = []

[dependencies]
burn-common = { path = "../burn-common", version = "0.15.0" }
burn-fusion = { path = "../burn-fusion", version = "0.15.0", optional = true }
burn-tensor = { path = "../burn-tensor", version = "0.15.0", features = [
  "cubecl",
] }
cubecl = { workspace = true, features = ["linalg"] }

bytemuck = { workspace = true }
derive-new = { workspace = true }
half = { workspace = true, features = ["bytemuck"] }
log = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
spin = { workspace = true }

# Template
serde = { workspace = true }
text_placeholder = { workspace = true, features = ["struct_context"] }

burn-tensor-testgen = { path = "../burn-tensor-testgen", version = "0.15.0", optional = true }
hashbrown = { workspace = true }

# When exporting tests
burn-autodiff = { path = "../burn-autodiff", version = "0.15.0", default-features = false, optional = true }
burn-ndarray = { path = "../burn-ndarray", version = "0.15.0", optional = true }
serial_test = { workspace = true, optional = true }

[package.metadata.docs.rs]
features = ["doc"]
